#!/usr/bin/env python
"""
Drifting Recognition Software

Created as project on FIT BUT Brno, December 2017
Authors:
    Matej Marusak xmarus06@stud.fit.vutbr.cz
    Andrej Barna  xbarna01@stud.fit.vutbr.cz
"""


import signal
from bluetooth import BluetoothSocket, RFCOMM


def get_values(line):
    """Parse out all three axis from one line"""
    values = line[1:].split()
    x = values[0][:-1]
    y = values[1][:-1]
    z = values[2][:-1]
    return (int(x), int(y), int(z))


class States:
    """Class simulating state automaton with hybrid states.
       Is able to remember current state of car as well as last and possible next.
    """
    P_STOP = 0
    STOP = 1
    P_STRAIGHT = 2
    STRAIGHT = 3
    P_RIGHT_DRIFT = 4
    RIGHT_DRIFT = 5
    P_LEFT_DRIFT = 6
    LEFT_DRIFT = 7

    SLOWING_C = 5

    NAMES = ['STOP', 'STOP', 'STRAIGHT', 'STRAIGHT', 'RIGHT_DRIFT',
             'RIGHT_DRIFT', 'LEFT_DRIFT', 'LEFT_DRIFT']

    def __init__(self):
        self.current = 1
        self.last_state = 1

    def do_step(self, x, y, z):
        """Based on rules, decides what is current state based on previous.
        Can set up prediction for the future state.
        """
        score = x + y + z
        # Staying still
        if abs(score) < 50:
            if self.current in [States.P_STOP, States.STOP]:
                self.current = States.STOP
            else:
                self.last_state = self.current
                self.current = States.P_STOP

        # Straight moving
        """
        Straight == forward or back moving, moving into corners without drifting
        the wheels.
        It is possible to recognize these movements with a little tweaking.
        """
        if ((x > 5000 or x < -5000) and abs(y) < 1000  and abs(z) < 10000):
            if self.current in [States.P_STRAIGHT, States.STRAIGHT]:
                self.current = States.STRAIGHT
            else:
                self.last_state = self.current
                self.current = States.P_STRAIGHT

        # Right drifting
        elif (x > 5000 and y > 5000) or z > 9000 or (y > 5000 and z > 5000):
            if self.current in [States.P_RIGHT_DRIFT, States.RIGHT_DRIFT]:
                self.current = States.RIGHT_DRIFT
            else:
                self.last_state = self.current
                self.current = States.P_RIGHT_DRIFT

        # Left drifting
        elif (x < -5000 and y < -5000) or z < -9000 or (y < -5000 and z < -5000):
            if self.current in [States.P_LEFT_DRIFT, States.LEFT_DRIFT]:
                self.current = States.LEFT_DRIFT
            else:
                self.last_state = self.current
                self.current = States.P_LEFT_DRIFT
        else:
            if self.current in [States.P_STRAIGHT, States.STRAIGHT]:
                self.current = States.STRAIGHT
            else:
                self.last_state = self.current
                self.current = States.P_STRAIGHT

    def name_state(self):
        """Translates state to human readable names."""
        use_name = self.current
        # Transient state
        if self.current % 2 == 0:
            use_name = self.last_state
        return States.NAMES[use_name]


def parsa_data(data, state):
    """Data coming from BT are a bit messy, we need to split them to lines."""
    while ("{" in data and "}" in data):
        line = data[data.find('{'):data.find('}') + 1]
        x, y, z = get_values(line)
        state.do_step(x, y, z)
        print(state.name_state())
        data = data[data.find('}') + 1:]
    return data


def finish_up(signum, frame):
    """When this script is killed, close BT socket."""
    signal.signal(signal.SIGINT, original_sigint)
    sock.close()


# State automaton
state = States()

# Signals processing when script gets killed
original_sigint = signal.getsignal(signal.SIGINT)
signal.signal(signal.SIGINT, finish_up)

# Connect to BT socket
sock = BluetoothSocket(RFCOMM)
sock.connect(("98:D3:32:30:AB:5C", 1))

data = sock.recv(165)
data = data[data.find('}') + 1:]
# Main loop - receive data, when full entry came, set up new state
while True:
    data += sock.recv(165)
    data = parsa_data(data, state)

sock.close()
